// Database types - will be auto-generated by Supabase CLI
export interface Database {
	public: {
		Tables: {
			products: {
				Row: {
					id: string;
					title: string;
					description?: string;
					price: number;
					original_price?: number;
					currency: string;
					condition: 'new' | 'like_new' | 'good' | 'fair';
					size?: string;
					brand?: string;
					color?: string;
					like_count: number;
					view_count: number;
					created_at: string;
					updated_at: string;
					shipping_available: boolean;
					shipping_price?: number;
					city?: string;
					location?: string;
					thumbnail_url?: string;
					images?: string[];
					tags?: string[];
					seller_id: string;
				};
				Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'>;
				Update: Partial<Database['public']['Tables']['products']['Insert']>;
			};
			users: {
				Row: {
					id: string;
					username: string;
					full_name?: string;
					avatar_url?: string;
					bio?: string;
					verified: boolean;
					seller_verified: boolean;
					seller_rating?: number;
					total_sales: number;
					follower_count: number;
					following_count: number;
					created_at: string;
					updated_at: string;
					account_type?: 'personal' | 'brand';
					onboarding_completed?: boolean;
				};
				Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>;
				Update: Partial<Database['public']['Tables']['users']['Insert']>;
			};
			likes: {
				Row: {
					id: string;
					user_id: string;
					product_id: string;
					created_at: string;
				};
				Insert: Omit<Database['public']['Tables']['likes']['Row'], 'id' | 'created_at'>;
				Update: Partial<Database['public']['Tables']['likes']['Insert']>;
			};
			cart_items: {
				Row: {
					id: string;
					user_id: string;
					product_id: string;
					quantity: number;
					created_at: string;
					updated_at: string;
				};
				Insert: Omit<Database['public']['Tables']['cart_items']['Row'], 'id' | 'created_at' | 'updated_at'>;
				Update: Partial<Database['public']['Tables']['cart_items']['Insert']>;
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
	};
}

// Helper types
export type Product = Database['public']['Tables']['products']['Row'] & {
	seller?: User;
	likes?: { count: number }[];
	is_liked?: boolean[];
};

export type User = Database['public']['Tables']['users']['Row'];

export type CartItem = Database['public']['Tables']['cart_items']['Row'] & {
	product?: Product;
};